services:
  apm-server:
    image: elastic/apm-server:7.17.22
    container_name: ninja.apm
    depends_on:
      - elasticsearch
      - kibana
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
      - 8300:8200
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana:5601
        -E output.elasticsearch.hosts=["elasticsearch:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    networks:
      - ninja.elastic

  elasticsearch:
    image: elasticsearch:8.14.1
    container_name: ninja.elasticsearch
    restart: always
    environment:
      - ELASTIC_PASSWORD=pass
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
      # - xpack.security.enrollment.enabled=false
      - xpack.security.enabled=false
    ports:
      - 9300:9200
    volumes:
      - ninja.elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - ninja.elastic

  kibana:
    image: kibana:8.14.1
    restart: always
    container_name: ninja.kibana
    ports:
      - "5201:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
    networks:
      - ninja.elastic

  fluent-bit:
    image: fluent/fluent-bit
    container_name: ninja.fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - elasticsearch
    networks:
      - ninja.elastic

networks:
  ninja.elastic:
    driver: bridge

volumes:
  ninja.elasticsearch_data:

